// AUTO-GENERATED VALIDATOR  CLASS -  Tools 1.0
// This class was generated by a TOOL !

using System.Collections;
using Microsoft.VisualBasic.CompilerServices;

namespace FSM
{
    // make sure that contact object is valid
    public class EngineerAbsenceValidator : BaseValidator
    {
        public void Validate(Entity.EngineerAbsence.EngineerAbsence oEA)
        {
            // make sure that contact object is valid
            if (oEA.Errors.Count > 0)
            {
                foreach (DictionaryEntry de in oEA.Errors)
                    AddCriticalMessage(Conversions.ToString(de.Value));
            }

            // If oEngineerAbsence.Exists = False Then
            // If Not Database.Utilities.IsPrimaryKeyUnique("EngineerAbsenceID", oEngineerAbsence.EngineerAbsenceID, "tblEngineerAbsence") Then
            // Me.AddCriticalMessage(ErrorMsg.AlreadyExists("EngineerAbsenceID"))
            // End If
            // End If

            // ok now check business logic of contact

            // TO-DO: Work for developer ... add validation code for the entity here

            var e = new Entity.Engineers.Engineer();
            e = App.DB.Engineer.Engineer_Get(Conversions.ToInteger(oEA.EngineerID));
            if ((oEA.EngineerID ?? "") == "-1")
            {
                AddCriticalMessage(ErrorMsg.FieldRequired("Engineer"));
            }

            if (oEA.AbsenceTypeID == -1)
            {
                AddCriticalMessage(ErrorMsg.FieldRequired("Absence Type"));
            }

            if (oEA.MorningSlots < 0)
            {
                AddCriticalMessage(ErrorMsg.NegativeNumber("Morning Slots"));
            }

            if (oEA.AfternoonSlots < 0)
            {
                AddCriticalMessage(ErrorMsg.NegativeNumber("Afternoon Slots"));
            }

            if (ValidatorMessages.CriticalMessages.Count > 0)
            {
                throw new ValidationException(this);
            }
        }
    }
}