

'AUTO-GENERATED VALIDATOR  CLASS -  Tools 1.0
'This class was generated by a TOOL !




Public Class UserAbsenceValidator
    'make sure that contact object is valid
    Inherits BaseValidator

    Public Sub Validate(ByVal oEA As Entity.UserAbsence.UserAbsence)

        'make sure that contact object is valid
        If oEA.Errors.Count > 0 Then
            Dim de As DictionaryEntry
            For Each de In oEA.Errors
                Me.AddCriticalMessage(CStr(de.Value))
            Next
        End If

        'If oUserAbsence.Exists = False Then
        'If Not Database.Utilities.IsPrimaryKeyUnique("UserAbsenceID", oUserAbsence.UserAbsenceID, "tblUserAbsence") Then
        'Me.AddCriticalMessage(ErrorMsg.AlreadyExists("UserAbsenceID"))
        'End If
        'End If

        'ok now check business logic of contact

        'TO-DO: Work for developer ... add validation code for the entity here


        If oEA.UserID = "-1" Then
            AddCriticalMessage(ErrorMsg.FieldRequired("User"))
        End If

        If oEA.AbsenceTypeID = -1 Then
            AddCriticalMessage(ErrorMsg.FieldRequired("Absence Type"))
        End If

        If Me.ValidatorMessages.CriticalMessages.Count > 0 Then
            Throw New ValidationException(Me)
        End If

    End Sub


End Class

