UPDATE tblsettings
SET WorkingHoursStart = ?WorkingHoursStart,
WorkingHoursEnd = ?WorkingHoursEnd,
MileageRate = ?MileageRate,
PartsMarkup = ?PartsMarkup,
RatesMarkup = ?RatesMarkup,
CalloutPrefix = ?CalloutPrefix,
MiscPrefix = ?MiscPrefix,
PPMPrefix = ?PPMPrefix,
QuotePrefix = ?QuotePrefix,
TimeSlot =?TimeSlot,
InvoicePrefix = ?InvoicePrefix,
RecallVariable =?RecallVariable,
PartsImportMarkup=?PartsImportMarkup,
ServiceFromLetterPrefix=?ServiceFromLetterPrefix